---
mapSizeWidth: 100
mapSizeHeight: 20
settings:
  1:
    symbol: "W"
    maxInTitle: "30"
    weightLoss: "5"
    legend: "*olf"
    showOnMap: "true"
    EatProbability_FamilyId_13: "10"
    EatProbability_FamilyId_14: "40"
    maxWeight: "50"
    speed: "3"
    modeOfNutrition: "CARNIVORES"
    EatProbability_FamilyId_7: "15"
    EatProbability_FamilyId_6: "10"
    EatProbability_FamilyId_9: "80"
    weightForFull: "8"
    EatProbability_FamilyId_8: "60"
    EatProbability_FamilyId_10: "60"
    EatProbability_FamilyId_11: "70"
    EatProbability_FamilyId_12: "15"
    name: "Wolf"
  2:
    symbol: "A"
    maxInTitle: "30"
    weightLoss: "1.5"
    legend: "*naconda"
    showOnMap: "true"
    EatProbability_FamilyId_14: "10"
    maxWeight: "15"
    speed: "1"
    modeOfNutrition: "CARNIVORES"
    EatProbability_FamilyId_9: "40"
    weightForFull: "3"
    EatProbability_FamilyId_8: "20"
    name: "Anaconda"
    EatProbability_FamilyId_3: "15"
  3:
    symbol: "F"
    maxInTitle: "30"
    weightLoss: "0.8"
    legend: "*ox"
    showOnMap: "true"
    EatProbability_FamilyId_14: "60"
    EatProbability_FamilyId_15: "40"
    maxWeight: "8"
    speed: "2"
    modeOfNutrition: "CARNIVORES"
    EatProbability_FamilyId_9: "90"
    weightForFull: "2"
    EatProbability_FamilyId_8: "70"
    name: "Fox"
  4:
    symbol: "B"
    maxInTitle: "5"
    weightLoss: "50"
    legend: "*ear"
    showOnMap: "true"
    EatProbability_FamilyId_13: "20"
    EatProbability_FamilyId_14: "10"
    maxWeight: "500"
    speed: "2"
    modeOfNutrition: "CARNIVORES"
    EatProbability_FamilyId_7: "80"
    EatProbability_FamilyId_6: "40"
    EatProbability_FamilyId_9: "90"
    weightForFull: "80"
    EatProbability_FamilyId_8: "80"
    EatProbability_FamilyId_10: "70"
    EatProbability_FamilyId_11: "70"
    EatProbability_FamilyId_12: "50"
    name: "Bear"
    EatProbability_FamilyId_2: "80"
  5:
    symbol: "E"
    maxInTitle: "20"
    weightLoss: "0.6"
    legend: "*agle"
    showOnMap: "true"
    EatProbability_FamilyId_14: "80"
    maxWeight: "6"
    speed: "3"
    modeOfNutrition: "CARNIVORES"
    EatProbability_FamilyId_9: "90"
    weightForFull: "1"
    EatProbability_FamilyId_8: "90"
    name: "Eagle"
    EatProbability_FamilyId_3: "10"
  6:
    modeOfNutrition: "HERBIVORES"
    symbol: "H"
    maxInTitle: "20"
    weightForFull: "60"
    weightLoss: "40"
    legend: "*orse"
    name: "Horse"
    showOnMap: "true"
    maxWeight: "400"
    EatProbability_FamilyId_16: "100"
    speed: "4"
  7:
    modeOfNutrition: "HERBIVORES"
    symbol: "D"
    maxInTitle: "20"
    weightForFull: "50"
    weightLoss: "30"
    legend: "*eer"
    name: "Deer"
    showOnMap: "true"
    maxWeight: "300"
    EatProbability_FamilyId_16: "100"
    speed: "4"
  8:
    modeOfNutrition: "HERBIVORES"
    symbol: "R"
    maxInTitle: "150"
    weightForFull: "0.45"
    weightLoss: "0.2"
    legend: "*abbit"
    name: "Rabbit"
    showOnMap: "true"
    maxWeight: "2"
    EatProbability_FamilyId_16: "100"
    speed: "2"
  9:
    modeOfNutrition: "OMNIVOROUS"
    symbol: "M"
    maxInTitle: "500"
    weightForFull: "0.01"
    weightLoss: "0.005"
    legend: "*ouse"
    name: "Mouse"
    showOnMap: "true"
    EatProbability_FamilyId_15: "90"
    maxWeight: "0.05"
    EatProbability_FamilyId_16: "100"
    speed: "1"
  10:
    modeOfNutrition: "HERBIVORES"
    symbol: "G"
    maxInTitle: "140"
    weightForFull: "10"
    weightLoss: "6"
    legend: "*oat"
    name: "Goat"
    showOnMap: "true"
    maxWeight: "60"
    EatProbability_FamilyId_16: "100"
    speed: "3"
  11:
    modeOfNutrition: "HERBIVORES"
    symbol: "S"
    maxInTitle: "140"
    weightForFull: "15"
    weightLoss: "7"
    legend: "*heep"
    name: "Sheep"
    showOnMap: "true"
    maxWeight: "70"
    EatProbability_FamilyId_16: "100"
    speed: "3"
  12:
    symbol: "O"
    maxInTitle: "50"
    weightLoss: "40"
    legend: "h*g"
    showOnMap: "true"
    EatProbability_FamilyId_15: "90"
    maxWeight: "400"
    EatProbability_FamilyId_16: "100"
    speed: "2"
    modeOfNutrition: "OMNIVOROUS"
    EatProbability_FamilyId_9: "50"
    weightForFull: "50"
    name: "Hog"
  13:
    modeOfNutrition: "HERBIVORES"
    symbol: "U"
    maxInTitle: "10"
    weightForFull: "0.15"
    weightLoss: "70"
    legend: "b*ffalo"
    name: "Buffalo"
    showOnMap: "true"
    maxWeight: "700"
    EatProbability_FamilyId_16: "100"
    speed: "4"
  14:
    modeOfNutrition: "OMNIVOROUS"
    symbol: "K"
    maxInTitle: "200"
    weightForFull: "0.15"
    weightLoss: "0.1"
    legend: "duc*"
    name: "Duck"
    showOnMap: "true"
    EatProbability_FamilyId_15: "90"
    maxWeight: "1"
    EatProbability_FamilyId_16: "100"
    speed: "4"
  15:
    modeOfNutrition: "HERBIVORES"
    symbol: "C"
    maxInTitle: "1000"
    weightLoss: "0.001"
    legend: "*aterpillar"
    name: "Caterpillar"
    showOnMap: "true"
    maxWeight: "0.01"
    EatProbability_FamilyId_16: "100"
  16:
    symbol: "P"
    maxInTitle: "1000"
    legend: "*lants"
    name: "Plants"
    maxWeight: "200"
map:
  1: "...................................................~~..............................................."
  2: "..................................................~~................................................"
  3: "......@.@......................................~~~.................................................."
  4: "......@@@~~~..................................~~...........................@.@......................"
  5: "........@..~~~..............................~~~~~~..........................@@@.......~~............"
  6: ".............~~...........................@@~...~~~.................................~~~~............"
  7: "..............~~.........~~~~~~@@.......@@~.......~~.......@........................~~~......~~@...."
  8: "...............~~~~.....~~~...~~@@@@..@@@~.........~~........................................~@....."
  9: "..................~~....~~......~~@@@@@@~...........~~.............................................."
  10: "..................~~~~~~..........~~~~~~.............~~............................................."
  11: "..................~~..................................~~............................................"
  12: ".................~~....................................~~.........................@@@@.............."
  13: "................~~......................................~~~~~~...................@@@@@@............."
  14: "...@@..........~~............................................~~.................~@@@@@@............."
  15: "...............~~........@....................................~~.............~~~~@@@@..............."
  16: "..............~~.........@@@................@@.................~~...........~~......................"
  17: ".............~~...........@@@..............@@@..................~~........~~........................"
  18: "............~~............@@@....................................~~....~~~.........................."
  19: "............~~....................................................~~~~~............................."
  20: "............~~......................................................................................"
mapColor:
  DEFAULT: "FONT_GRAY"
  MOUNTAIN: "FONT_GRAY"
  RIVER: "FONT_BLUE"
  FIELD: "FONT_GREEN"
mapLegend:
  DEFAULT: "@"
  MOUNTAIN: "@"
  RIVER: "~"
  FIELD: "."
statisticLine:
  LINE_UP_RIGHT: "╚"
  LINE_DOWN_LEFT: "╗"
  LINE_DOWN_RIGHT: "╔"
  LINE_HORIZONTAL: "═"
  LINE_UP_LEFT: "╝"
  LINE_VERTICAL: "║"
  LINE_VERTICAL_LEFT: "╣"
  LINE_VERTICAL_RIGHT: "╠"
mapLegendRevers: {}
mapColorBackGround: "BACK_WHITE"
statisticSizeOfNames: 12
statisticSizeFrameAfterNames: 20
statisticNameSymbol: "*"
statisticNameColorTurn: "FONT_DARK_BLUE"
statisticNameColorLine: "FONT_DARK_BROWN"
statisticNameColorPredator: "FONT_DARK_RED"
statisticNameColorHerbivore: "FONT_DARK_GREEN"
statisticNameColorOmnivorous: "FONT_VINOUS"
statisticNameColorUnknown: "FONT_GRAY"
statisticNumbersColor: "FONT_AMBER"
statisticNumbersPositiveColor: "FONT_DARK_GREEN"
statisticNumbersNegativeColor: "FONT_DARK_RED"
reproductionChance: 30
